version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: sindhuja_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin834
      POSTGRES_DB: job_application_db
    ports:
      - "5449:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: sindhuja_backend
    restart: always
    ports:
      - "3017:3017"
    depends_on:
      - postgres
    volumes:
      - ./Backend/uploads:/app/uploads

  employee-job:
    build: ./Employee-job
    container_name: sindhuja_employee_ui
    ports:
      - "8032:80"
    depends_on:
      - backend

  hr-job:
    build: ./HR-job
    container_name: sindhuja_hr_ui
    ports:
      - "8033:80"
    depends_on:
      - backend

volumes:
  pgdata:

